### ISSUE TITLE
Allow configurable cookie domain property

### ISSUE THREAD

**Issue by blumgart** [sidebase/nuxt-session#19]
### Describe the feature

I have two subdomains:

- frontend.example.com (Nuxt)
- backend.example.com (Strapi)

and the problem is this - from frontend.example.com no cookies are passed to backend.example.com. I need to send sessionId to Strapi and save to database.

If you add the `domain: ".example.com"` property, then the cookies are sent as expected.

https://github.com/sidebase/nuxt-session/blob/5cbbad4b0a7b5c4d721f72b8507c007c10e67d5b/src/runtime/server/middleware/session/index.ts#L9-L18

**Comment by BracketJohn** [comment]
Yeah, we'll support that! 

Do you want to have a try at implementing this? Else we can take over (:
