### ISSUE TITLE
How to configure Redis?

### ISSUE THREAD

**Issue by JacobArrow** [sidebase/nuxt-session#26]
Hello!

I'm looking for an example on how to configure the storage options to work with a Redis server through unstorage.
I am unable to figure out the syntax for configuring it inside the session.session.storageOptions setting.

**Comment by zoey-kaiser** [comment]
Hi @JacobArrow! 

In the current release we saldy only support memory storage (as we wanted to keep the scope smaller for the first release).

However we have a open PR that is working on integrating other storage possibilities here: https://github.com/sidebase/nuxt-session/pull/7

It is coming along very well and we hope to merge it soon! When we do so, we will include more documentation on the different storage options. You are free to look into the PR, give feedback on it and follow along!

**Comment by JacobArrow** [comment]
Thank you very much for the insight @zoey-kaiser! I will pay close attention to the PR :)

**Comment by BracketJohn** [comment]
Hey @JacobArrow, this works now, see the docs here: https://github.com/sidebase/nuxt-session#configuration Thanks tgo @Twitch0125 for implementing this 🎊 

Please let us know if you have any other problems with this, or open a new issue for future bug / features request!

**Comment by BracketJohn** [comment]
@JacobArrow here's the exact link to the relevant docs: https://github.com/sidebase/nuxt-session#example-of-using-a-different-storage-driver
