### ISSUE TITLE
Error in ipPinning.mjs middleware

### ISSUE THREAD

**Issue by JacobArrow** [sidebase/nuxt-session#30]
### Environment

- Operating System: `Linux`
- Node Version:     `v17.2.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `modules`, `css`, `build`, `i18n`, `pinia`, `session`, `dir`, `ignore`, `alias`, `vite`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.4-27807009.4ba6102`, `@pinia/nuxt@0.4.3`, `@nuxtjs/tailwindcss@6.1.3`, `@sidebase/nuxt-session@0.2.4`
- Build Modules:    `-`

### Reproduction

Update to newest version of nuxt-session

### Describe the bug

When I run `yarn dev` in my Nuxt project after updating this package, the server crashes and I get `503 Server Unavailable`

### Logs

```shell
file:///var/www/html/dune/.nuxt/dev/index.mjs:26
import { verify, argon2id, hash as hash$1 } from 'file:///var/www/html/dune/node_modules/argon2/argon2.js';
                 ^^^^^^^^
SyntaxError: Named export 'argon2id' not found. The requested module 'file:///var/www/html/dune/node_modules/argon2/argon2.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'file:///var/www/html/dune/node_modules/argon2/argon2.js';
const { verify, argon2id, hash: hash$1 } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```
```

**Comment by BracketJohn** [comment]
Hey @JacobArrow! 

Thanks for the issue (: We'll haver a loot at it ASAP!

@Voltra, maybe you want to check it out, as it's related to ipPinning?
