### ISSUE TITLE
Documentation to override Configuration

### ISSUE THREAD

**Issue by nengine** [sidebase/nuxt-session#42]
### Describe the feature

It would be helpful to have documentation of specific steps to override default configuration of nuxt-session.  I wanted to change default session expiration of 10 minutes to 1 hours for example.

**Comment by BracketJohn** [comment]
Hey @nengine 👋 

Thanks for the issue - have you checked out the readme config section? There's a config key exactly for what you are asking (i think)! 

Does tha resolve your request? (:

**Comment by BracketJohn** [comment]
Here's the exact link to the configuration: https://github.com/sidebase/nuxt-session#configuration

**Comment by nengine** [comment]
Thanks a lot @BracketJohn .  Very much appreciated.

**Comment by BracketJohn** [comment]
perfect - closing the issue now as answered!
