### ISSUE TITLE
Possibility to set secure flag for cookie depending on environment

### ISSUE THREAD

**Issue by re-mxp** [sidebase/nuxt-session#46]
### Describe the feature

At the moment it is only possible to use the `Local`-address to set the session cookie, because it's not allowed to set a non https cookie with the `secure` flag. 
![grafik](https://user-images.githubusercontent.com/71883104/204159335-fcbd5a0e-7e56-44b3-8289-5f8b2de5ced1.png)

I would like the possiblity to also use the `Network`-address:
![grafik](https://user-images.githubusercontent.com/71883104/204159323-a8e90228-6ef7-4d55-874f-bfbe6eefb6bd.png)

But it results in following error in the console:
![grafik](https://user-images.githubusercontent.com/71883104/204159051-50b5729e-d4be-4db6-95bf-0fd320c931dc.png)

Is it possible to make this line also configurable:
https://github.com/sidebase/nuxt-session/blob/main/src/runtime/server/middleware/session/index.ts#L15

**Comment by BracketJohn** [comment]
Sure thing - would you line to controbute a PR to add this? (:

**Comment by re-mxp** [comment]
With pleasure :)

**Comment by BracketJohn** [comment]
Amazing, the feature will be very welcome and should be quite smallish to implement:
- expand module config with `cookieSecure: boolean` flag, default value `true`
- call useRuntimeConfig to consume `cookieSecure` in the line you linked above
- expand the README configuration section to document this feature

**Comment by BracketJohn** [comment]
Nope - there's another way to do it in open source work: 
1. Fork the repository (click here https://github.com/sidebase/nuxt-session/fork)
2. Clone the fork, checkout a new branch, add your changes, commit and push them
3. Once you're happy, come back to this repo, click open PR and you'll be able to select the branch from your work

As far as I know this mostly comes down to permissions, here's an article explaining this: https://opensource.com/article/19/11/first-open-source-contribution-fork-clone

Does that help / can you continue with that information? (:

**Comment by re-mxp** [comment]
Yes thanks for the information :)
