### ISSUE TITLE
How to use Session in Nuxt3 middleware

### ISSUE THREAD

**Issue by nengine** [sidebase/nuxt-session#50]
### Ask your question

When I refresh the web browser, wanted to read session value from a middleware. I tried like below but not getting any value. An example of how to use useSession in the serverside middleware would be great.  

```
export default defineNuxtRouteMiddleware(async (to, from) => {
  const { session } = await useSession()
  console.log(session.value)
})
```

**Comment by re-mxp** [comment]
Route Middleware is executed on server and client side. Check if you are on the server with `process.server` and use following nuxt composable https://nuxt.com/docs/api/composables/use-request-event.

```js
if (process.server) {
    const event = useRequestEvent();
    const { session } = event.context;
   // Access values in session
   ....
}
```

**Comment by nengine** [comment]
You rock @re-mxp. Thanks a lot.

**Comment by smorcuend** [comment]
Hi everyone!

What about server middleware?

Is any manner to access session data inside server middleware code?

```typescript
// ./server/middleware/session.ts
export default defineEventHandler((event) => {
  console.log(event.context.session) // undefined
})

```

**Comment by BracketJohn** [comment]
Hey @smorcuend 👋 

This sadly is a known problem in the way nitro / nuxt adds (module) middlewares. The session middleware currently runs after your middlewares, so there's no access to the session in your middlewares.

We've opened an issue for this in the nuxt repo here: 

Once that is fixed / there is a documented way to resolve this we will roll it out here.

**Comment by BananaAcid** [comment]
@BracketJohn could you please add this info to the readme? I was jsut going to post an issue about this (took me last 2 hours to pinpoint this problem).

Is there an alternative way?
