### ISSUE TITLE
Single session per application

### ISSUE THREAD

**Issue by Darkside73** [sidebase/nuxt-session#65]
### Ask your question

After installing module I get different session ids (and essentially separate sessions) for each API request

```ts
// nuxt.config.ts
export default defineNuxtConfig({
  modules: [
    @sidebase/nuxt-session'
  ]
})
```

```ts
// server/api/foo.get.ts
export default eventHandler((event) => {
  console.log('/foo', event.context.session.id)
  return 'foo'
})

// server/api/bar.get.ts
export default eventHandler((event) => {
  console.log('/bar', event.context.session.id)
  return 'bar'
})
```

```vue
<script setup lang="ts">
const foo = await useFetch('/api/foo')
const bar = await useFetch('/api/bar')
</script>

<template>
  <div>
    {{ foo }}
    <br>
    {{ bar }}
  </div>
</template>
```

Server stdout
```
/foo ZwS1Mbg0mhwZ3Fr51uu0HueqW2QqN2ODvKPtr-nbMYfLvpA7UUm-_mjzP7yuELJb                                                                                                      
/bar vksnahk5IG8XfXo5B1LQbTFtUrtB8sjThpRM8r3CVuQLGJ4PMxH0Q0qe-dUq9Fz9  
```

Each request generates new session id. Is it possible achieve single session?

**Comment by BananaAcid** [comment]
Taken your test, calling the following code from the chrome-dev-console multiple times, gives me different session ids in  log output each time:

```js
await fetch('/api/foo', {
  method: 'GET',
  credentials: 'include'
});
```

Seems like, the session does not actually exist. There does not seem to be an option to set the session cookie name.

**Comment by Darkside73** [comment]
Thanks. The issue was in outdated dependencies (nuxt itself I think)

**Comment by BananaAcid** [comment]
@Darkside73 How do you feel about `This can be mitigated by changing the plugin's config (a note about it, should probably be added to readme):` ?
